function createfigure(x1, y1, z1, x2, y2, z2)
%CREATEFIGURE(X1,Y1,Z1,X2,Y2,Z2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Z2:  vector of z data
 
%  Auto-generated by MATLAB on 08-Nov-2006 12:05:03
 
%% Create figure
figure1 = figure;
 
%% Create axes
axes1 = axes(...
  'CameraPosition',[-124.8 33.25 2.197e+005],...
  'CameraUpVector',[0.47 0.6925 2.309e+004],...
  'XTick',[-122.8 -122.6 -122.4 -122.2 -122 -121.8],...
  'Parent',figure1);
axis(axes1,[-122.8 -121.8 36.6 37.4 0 3e+004]);
xlabel(axes1,'Longitude, ^o');
ylabel(axes1,'Latitude, ^o');
zlabel(axes1,'Concentration, cm^-^3');
grid(axes1,'on');
hold(axes1,'all');
 
%% Create plot3
plot31 = plot3(x1,...
  y1,z1,...
  'LineStyle','none',...
  'Marker','.');
 
%% Create plot3
plot32 = plot3(x2,y2,z2);
 
